# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-10 21:06
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=12, unique=True),
        ),
    ]
